format_version: 3

pipelines:
  myawesome-service-1-build-dev:
    group: TEAMNAME
    materials:
      mygit:
        git: https://github.com/vjmax/hello-world.git
        branch: master
    stages:
    - build:
        clean_workspace: true
        jobs:
            tasks:
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package"
