format_version: 3

pipelines:
  myawesome-service-1-build-dev:
    group: TEAMNAME
    materials:
      mygit:
        git: https://github.com/vjmax/hello-world.git
        branch: develop
    environment_variables:
      DOCKER_REGISTRY: 479580041174.dkr.ecr.ap-south-1.amazonaws.com
      IMAGE_NAME: myawesome-service-1
    stages:
    - build:
        clean_workspace: true
        jobs:
          build:
            elastic_profile_id: myawesome-java-8
            artifacts:
            - build:
                source: image_ref
            tasks:
            - exec:
                command: bash
                arguments:
                - "-c"
                - "mvn clean package"
