format_version: 10
pipelines:
  prod-java-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-228b45a:
        git: https://github.com/vjmax/hello-world.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - prod-Build-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          prod-Build-job:
            timeout: 0
            resources:
            - Tomcat2
            tasks:
            - exec:
                arguments:
                - clean
                - install
                command: mvn
                run_if: passed
    - Prod-Deploy-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Prod-deployy-job:
            timeout: 0
            resources:
            - Tomcat1
            tasks:
            - exec:
                arguments:
                - tomcat7:deploy
                command: mvn
                run_if: passed
